podTemplate(label: 'jnlp-slave', cloud: 'kubernetes', containers: [
    containerTemplate(
        name: 'jnlp', 
        image: 'xtdockerhub.com/ops/jenkins-slave', 
        alwaysPullImage: true 
    ),
  ],
  volumes: [
    hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'),
    hostPathVolume(mountPath: '/usr/bin/docker', hostPath: '/usr/bin/docker'),
    hostPathVolume(mountPath: '/usr/local/jdk', hostPath: '/usr/local/jdk'),
    hostPathVolume(mountPath: '/usr/local/maven', hostPath: '/usr/local/maven'),
  ],
  imagePullSecrets: ['registry-pull-secret'],
) 
{
  node("jnlp-slave"){
      stage('Git Checkout'){
         checkout([$class: 'GitSCM', branches: [[name: '${Tag}']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'f6698074-d226-4fe7-a915-ebc8510eab63', url: 'https://github.com/AsiaYoYo/solo.git']]])
      }
      stage('Unit Testing'){
      	echo "Unit Testing..."
      }
      stage('Maven Build'){
          sh "mvn clean package -Dmaven.test.skip=true"
      }
      stage('Build and Push Image'){
          sh '''
          echo "192.168.11.211 xtdockerhub.com" >> /etc/hosts
          docker login -u dev -p Dev12345 xtdockerhub.com
          docker build -t xtdockerhub.com/project/solo:${Tag} -f deploy/Dockerfile .
          docker push xtdockerhub.com/project/solo:${Tag}
          '''
      }
      stage('Deploy to K8S'){
          sh '''
          cd deploy 
          sed -i "/xtdockerhub.com/{s/latest/${Tag}/}" deploy.yaml
          sed -i "s/environment/${Env}/" deploy.yaml
          '''
          kubernetesDeploy configs: 'deploy/deploy.yaml', kubeConfig: [path: ''], kubeconfigId: 'ac5bf8e1-c74f-406b-8565-f15e664b4b9f', secretName: '', ssh: [sshCredentialsId: '*', sshServer: ''], textCredentials: [certificateAuthorityData: '', clientCertificateData: '', clientKeyData: '', serverUrl: 'https://']
      }
      stage('Testing'){
          echo "Testing..."
      }
  }
}

